from enum import Enum


class EInstruction(Enum):
    REQUIRE_DATA_TRAFFIC_PERIOD = 0,
    REQUIRE_DATA_CURRENT_TRAFFIC_STATUS = 1,
    REQUIRE_DATA_CURRENT_TRAFFIC_SIGNAL_STATE = 2,

    SEND_DATA_TRAFFIC_PERIOD = 3,
    SEND_DATA_CURRENT_TRAFFIC_STATUS = 4,
    SEND_DATA_CURRENT_TRAFFIC_SIGNAL_STATE = 5,

    SWITCH_MODE = 6


if __name__ == "__main__":
    print(EInstruction.EAST.value)
